### ISSUE TITLE
Documentation in comments leads to out-of-date URLs

### ISSUE THREAD

**Issue by michaelherold** [amzn/login-and-pay-with-amazon-sdk-ruby#5]
All of the non-trivial `@see` declarations throughout the codebase lead to URLs that redirect to https://payments.amazon.com/documentation.

It would be very helpful if these were updated to go to specific pages within the documentation instead of the documentation index.

**Comment by khoja-amazon** [comment]
Yes, we recently launched a new documentation page (https://payments.amazon.com/documentation). The URLs will be updated with the next update of the library.

**Comment by khoja-amazon** [comment]
The documentation links have been updated. Thanks!
