### ISSUE TITLE
More doc please

### ISSUE THREAD

**Issue by keynan** [amzn/login-and-pay-with-amazon-sdk-ruby#8]
What this could really use is a rails app with nothing but the bare bones to perform a transaction. Something I could checkout, plug-in a merchant / seller ID and make test purchases with against either sandbox or production.

**Comment by samir-khoja** [comment]
Thank you for your suggestion! We will definitely look to create additional developer resources in the future.

**Comment by b3ccio** [comment]
+1 for sample Rails 5 app.

@samir-khoja is this repo still supported? https://github.com/amzn/amazonpay-express-demo/tree/master/ruby

Thanks.

**Comment by bjguillot** [comment]
@b3ccio, thanks for the extra push.  We still support it, but it's long due for an update.
